### ISSUE TITLE
IE jankiness

### ISSUE THREAD

**Issue by iuloshi** [cfpb/cfpb.github.io#30]
Per @virtix:

> The manual, as well as http://cfpb.github.io/, is quite janky in IE.  This is less of an issue for our target audience, but I would put it at the top of the queue.  The reason being is that I suspect this could get picked up broadly and it would be great if it also worked broadly.

[Design Manual issue](https://github.com/cfpb/design-manual/issues/199)

**Comment by cartagenae** [comment]
Internet Explorer is going to be discontinued. Microsoft is currently working on another web browser.
