### ISSUE TITLE
Open Source @CFPB--A Case Study

### ISSUE THREAD

**Issue by virtix** [cfpb/cfpb.github.io#34]
Tell the story of how we got to where we are today, using a timeline/sequence.  Some topics to consider covering are below.  Make sure to cover the more difficult challenges and address gaps and vision for the future.
- OS Definition
- Licensing
- Procurement
- FTE + OSS model vs. RFP
- Policy story
- Open by default
- Implementation
  - Hosting
    - internal
    - external
  - Publishing
    - problem with keeping multiple repos in synch
    - problem with having an open source version (public version) and private version
      - efficiency of development 
  - Workflow details
    - code reviews
    - pull requests
    - issue tracking
  - build and deployment
    - versioning releases
    - automated tests
    - continuous integration (Travis and Jenkins)
- Privacy, PRA, and PII
  - SORN
- Security
  - vulnerability risk
- Software Quality and Agency Reputation
- Accepting contributions / public collaboration
- Working with other agencies
  - DoD, WH, OMB, GSA, NASA,LoC
  - Fragmentation. Inconsistent.
#### General questions to answer in the study
- **What's missing?** 
- What's the strategy for the future?
- **What were the biggest hurdles?
- What is the impact to the Bureau, to other agencies?
- How can other business practices benefit from the open source collaboration model?
  - What are the risks?
- How does open source relate to and integrate with the Open Government and Open Data initiatives?

**Comment by toti1399** [comment]
Good

**Comment by anselmbradford** [comment]
Time and tides wait for no one, and alas time has eroded the relevance the great ideas in this thread had to the current status quo.
