### ISSUE TITLE
No way to find old articles from homepage

### ISSUE THREAD

**Issue by willbarton** [cfpb/cfpb.github.io#52]
I can't view more than the last four articles on the homepage (the one featured on the left, and three additional ones listed on the right). There's no obvious way to view older articles. If I go into an article I can see articles back to 2013.

Shouldn't there be an archive link or something on the homepage?

**Comment by Scotchester** [comment]
Yes.

**Comment by ascott1** [comment]
I want to bump this up. At the very least `/articles/` shouldn't 404.
