### ISSUE TITLE
Proposal: add a link to the consumer complaint database, get rid of the link to Collab

### ISSUE THREAD

**Issue by sonnakim** [cfpb/cfpb.github.io#76]
What are the team's thoughts on swapping out the collab link, which is no longer in active development anyway, with a link to the consumer complaint database? 

Here's what this could look like. 

![image](https://cloud.githubusercontent.com/assets/9451445/11852696/7f604a8e-a407-11e5-87a2-65a9f8ab6dd7.png)

#### Proposed copy
(This may change based on our product owner's feedback in the next few days.)

Consumer Complaint Database [link to /complaint database] 
View, sort and analyze thousands of complaints. Download the data yourself, or build on it using our API. 
Learn more [link to /data-use] | API docs [link to technical documentation]

Yea? Nay?

**Comment by Scotchester** [comment]
Let's take this discussion (which could get into sensitive topics) to GHE. Sonna, would you please re-post under CFPB/cfpb.github.io there? Thanks.
