### ISSUE TITLE
Server-side HTTPS enforcement for cfpb.github.io

### ISSUE THREAD

**Issue by konklone** [cfpb/cfpb.github.io#97]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

The site already works over HTTPS without errors: https://cfpb.github.io So this should be a trivial fix.

**Comment by ascott1** [comment]
Done!

**Comment by konklone** [comment]
Great, thanks for doing it!
